# Generated by Django 5.0 on 2023-12-24 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
